"""create medicine records table

Revision ID: 8bd1e9c52b4c
Revises: 854f65900589
Create Date: 2026-09-24 17:53:16.850240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd1e9c52b4c'
down_revision: Union[str, Sequence[str], None] = '854f65900589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('medicine_id', sa.Integer(), nullable=False),
    sa.Column('treatment_date', sa.Date(), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('veterinarian', sa.String(length=150), nullable=True),
    sa.Column('withdrawal_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicine_records_id'), 'medicine_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicine_records_id'), table_name='medicine_records')
    op.drop_table('medicine_records')
    # ### end Alembic commands ###
